// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// InjectableConfigGenerator
// **************************************************************************

// ignore_for_file: type=lint
// coverage:ignore-file

// This file will be generated by build_runner
// Run: flutter pub run build_runner build --delete-conflicting-outputs

import 'package:dio/dio.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import '../../data/datasources/local/auth_local_datasource.dart';
import 'register_module.dart';

extension GetItInjectableX on GetIt {
  // ignore: non_constant_identifier_names
  Future<GetIt> init({
    String? environment,
    EnvironmentFilter? environmentFilter,
  }) async {
    final gh = GetItHelper(this, environment, environmentFilter);

    final registerModule = _$RegisterModule();
    gh.lazySingleton<Dio>(() => registerModule.dio);
    gh.lazySingleton<FlutterSecureStorage>(() => registerModule.secureStorage);

    // Data sources
    gh.lazySingleton<AuthLocalDataSource>(
      () => AuthLocalDataSource(gh<FlutterSecureStorage>()),
    );

    return this;
  }
}

class _$RegisterModule extends RegisterModule {}
